### ISSUE TITLE
Cannot available yet?

### ISSUE THREAD

**Issue by ssun-g** [autodistill/autodistill-fastsam#1]
I downloaded it using the "pip install autodistill-fastsam" command, but it could not be executed.

```
ERROR: Could not find a version that satisfies the requirement autodistill-fastsam (from versions: none)
ERROR: No matching distribution found for autodistill-fastsam
```

Thank you for your hard work.

**Comment by capjamesg** [comment]
@ssun-g Thank you for the message! We're getting ready to distribute the package now. I will message here when it is published.

**Comment by artyaltanzaya** [comment]
Hello @ssun-g, I republished the package and fixed the problem. It should should work now!

**Comment by ssun-g** [comment]
It works perfectly!
Thank you for your help.
