### ISSUE TITLE
Getting an issue while using fastsam

### ISSUE THREAD

**Issue by Barath19** [autodistill/autodistill-fastsam#3]
, line 19, in run_command
    with subprocess.DEVNULL as DEVNULL:
AttributeError: __enter__

**Comment by artyaltanzaya** [comment]
Hello @Barath19 thanks for raising this. Will let you know once the changes are installable.

**Comment by capjamesg** [comment]
I have merged @artyaltanzaya's PR. We will be distributing an update to `autodistill-fastsam` soon. We will add a note here when the changes have been published.

**Comment by Barath19** [comment]
Thank you @capjamesg and @artyaltanzaya
